---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tbtc-dapp
  namespace: default
  labels:
    keel.sh/policy: all
    app: tbtc
    type: dapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tbtc
      type: dapp
  template:
    metadata:
      labels:
        app: tbtc
        type: dapp
    spec:
      containers:
      - name: tbtc-dapp
        image: gcr.io/keep-dev-fe24/tbtc-dapp
        ports:
          - containerPort: 80
        env:
        # TODO: ETH_WS_URL needs to be using wss:// instead of ws://, otherwise
        # insecure connection will be blocked.
        - name: ETH_WS_URL
          valueFrom:
            configMapKeyRef:
              name: eth-network-internal
              key: ws-url
        - name: ETH_CHAIN_ID
          valueFrom:
            configMapKeyRef:
              name: eth-network-internal
              key: network-id
