repos:
  - repo: local
    hooks:
    - id: lint-js
      name: 'lint js'
      entry: /usr/bin/env bash -c "npm run lint"
      files: '\.js$'
      language: script
      description: "Checks JS code according to the package's linter configuration"
