name: Contracts

on: [ push, pull_request ]

defaults:
  run:
    working-directory: ./contracts

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run compile
  test:
    runs-on: ubuntu-latest
    needs: compile
    steps:
    - uses: actions/checkout@v2
    - name: Get Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run compile
    - run: npm test
