name: Frontend

on:
  push:
    branches: [ master ]
  pull_request:

defaults:
  run:
    working-directory: ./frontend

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - run: npm run build
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - run: npm test
  deploy:
    needs: [lint-and-build, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - run: npm run build
    - name: Deploy static site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/build
        cname: redeem.finance
