name: tBTC dApp

on:
  push:
    branches: [ master ]

defaults:
  run:
    working-directory: ./tbtc-dapp

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build
      env:
        CI: false
    - name: Deploy static site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./tbtc-dapp/build
        cname: dapp.redeem.finance
